version: '3.9'

services:
  backend:
    image: profiler-backend
    build:
      context: ../profiler
    ports:
      - "3000:3000"
    env_file:
      - ../profiler/.env
    restart: unless-stopped

  frontend:
    image: profiler-frontend
    build:
      context: .
    ports:
      - "5173:80"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
